apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: evertonandrade-com-tls
spec:
  secretName: evertonandrade-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: evertonandrade.com
  dnsNames:
    - evertonandrade.com
    - www.evertonandrade.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - evertonandrade.com
          - www.evertonandrade.com